[LegalNotice]
Accepted=true

[Preferences]
WebUI\AuthSubnetWhitelist=0.0.0.0/0
WebUI\AuthSubnetWhitelistEnabled=true
WebUI\LocalHostAuth=false
Downloads\SavePath=/downloads
Downloads\TempPath=/downloads/temp
BitTorrent\DHT=true
BitTorrent\PeX=true
BitTorrent\LSD=true
